---
- name: install apache2
  apt: name=apache2

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: apache2 listen on port {{ http_port }}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
  notify:
    - restart apache2

- name: Configure Apache.
  lineinfile:
    dest: "/etc/apache2/ports.conf"
    regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"
    state: present
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "/etc/apache2/sites-available/vhosts.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlink in sites-enabled.
  file:
    src: "/etc/apache2/sites-available/vhosts.conf"
    dest: "/etc/apache2/sites-enabled/vhosts.conf"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled.
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost

#- name: apache2 virtualhost on port {{ http_port }}
#  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>" state=present
#  notify:
#    - restart apache2
