---
#- name: Install Transmission
#  apt:
#    name: transmission-daemon
#    state: present
#  tags: transmission

# Configuration
- name: Make sure transmission is not running
  service:
    name: transmission-daemon
    state: stopped
  ignore_errors: true
  tags: transmission

- debug: msg="User {{ transmission_user }}"

- name: add_transmission_user | adding transmission user to transmission group
  user:
    name="{{ transmission_user }}"
    groups=debian-transmission,pi
    append=yes


- name: Add downloads folder
  file:
    state: directory
    path: "{{ transmission_download_dir }}"
    owner: "{{ transmission_user }}"
    group: debian-transmission
    mode: 0775
  tags: transmission

- name: Copy tr-remove-done script
  template:
    src: templates/tr-remove-done.sh.j2
    dest: /usr/bin/tr-remove-done.sh
    owner: "{{ transmission_user }}"
    group: debian-transmission
    mode: "u=rwx,g=rx,o=x"
  become: true
  become_user: root

- name: Copy Transmission configuration
  template:
    src: templates/settings.json.j2
    dest: /etc/transmission-daemon/settings.json
  tags: transmission

- name: Add current user to transmission group
  user:
    name: "{{ transmission_user }}"
    groups: debian-transmission
    append: yes
  tags: transmission

- name: Download Custom Skin
  get_url:
    url: https://github.com/ronggang/transmission-web-control/raw/master/release/transmission-control-full.tar.gz
    dest: /tmp/customskin.tar.gz

- name: create /opt/trans-skin folder
  file:
    path: /opt/trans-skin
    owner: "{{ transmission_user }}"
    group: debian-transmission
    mode: "u=rwx,g=rx,o=rx"
    state: directory

- name: Extract downloaded archive
  unarchive:
    src: /tmp/customskin.tar.gz
    dest: /opt/trans-skin
    copy: no

- name: Create sudo crontab after restart
  cron:
    name: "Restart transmission on reboot (to ensure that it is running"
    special_time: reboot
    job: "systemctl restart transmission-daemon"


# Create transmission-daemon service
- name: create {{ service_name }} job
  template:
    src: transmission-daemon.service.j2
    dest: /etc/systemd/system/transmission-daemon.service
  register: install_config

- name: notify systemd of config changes
  command: systemctl daemon-reload
  when: install_config.changed == True

- name: Start transmission and set to start on startup
  service:
    name: transmission-daemon
    state: started
    enabled: yes
  ignore_errors: true
  tags: transmission